#!/usr/bin/env python3
"""Structural and portability quality gate for Skill Creator Juiced packages."""
from __future__ import annotations

import argparse
import sys
sys.dont_write_bytecode = True
import json
import re
from pathlib import Path

from skill_spec import read_text, validate_agent_skill

PLACEHOLDER_PATTERNS = [
    "TO" + "DO",
    "[" + "TO" + "DO",
    "replace" + " with actual",
    "placeholder" + " script",
    "example" + " asset",
    "api_" + "reference.md",
]
REQUIRED_BODY_TERMS = ["workflow", "output contract", "stop condition"]
MARKDOWN_LINK_RE = re.compile(r"\[[^\]]+\]\(([^)]+)\)")
TEXT_SUFFIXES = {".md", ".txt", ".py", ".yaml", ".yml", ".json", ".template", ".sh"}


def local_markdown_links(target: Path, markdown_file: Path):
    text = read_text(markdown_file)
    for raw in MARKDOWN_LINK_RE.findall(text):
        ref = raw.split("#", 1)[0].strip()
        if not ref or "://" in ref or ref.startswith(("#", "/", "mailto:")):
            continue
        yield markdown_file, ref, (markdown_file.parent / ref).resolve()


def run_gate(target: Path, profile: str) -> dict:
    errors: list[str] = []
    warnings: list[str] = []
    inspected: list[str] = []

    if not target.is_dir():
        return {"status": "fail", "profile": profile, "errors": [f"target is not a directory: {target}"], "warnings": [], "inspected": []}

    skill_files = [p for p in target.rglob("SKILL.md") if ".git" not in p.parts]
    if skill_files != [target / "SKILL.md"]:
        errors.append(f"expected exactly one root SKILL.md, found {len(skill_files)}")
        return {"status": "fail", "profile": profile, "errors": errors, "warnings": warnings, "inspected": [str(p) for p in skill_files]}

    portability = validate_agent_skill(target, profile)
    errors.extend(portability["errors"])
    warnings.extend(portability["warnings"])

    skill_md = target / "SKILL.md"
    inspected.append(str(skill_md))
    text = read_text(skill_md)
    lower_text = text.lower()
    for term in REQUIRED_BODY_TERMS:
        if term not in lower_text:
            warnings.append(f"SKILL.md does not visibly include '{term}'")

    for path in target.rglob("*"):
        if ".git" in path.parts:
            continue
        rel = path.relative_to(target)
        if "__pycache__" in path.parts or path.suffix in {".pyc", ".pyo"}:
            errors.append(f"cache/generated bytecode must not be packaged: {rel}")
            continue
        if not path.is_file() or path.suffix.lower() not in TEXT_SUFFIXES:
            continue
        content = read_text(path)
        if str(rel).startswith("assets/templates/"):
            continue
        for pattern in PLACEHOLDER_PATTERNS:
            if pattern.lower() in content.lower() or pattern.lower() in str(rel).lower():
                errors.append(f"placeholder/scaffold marker '{pattern}' found in {rel}")
                break

    for md in target.rglob("*.md"):
        inspected.append(str(md))
        for source, link, resolved in local_markdown_links(target, md):
            if not str(resolved).startswith(str(target.resolve())):
                errors.append(f"local link leaves package: {source.relative_to(target)} -> {link}")
            elif not resolved.exists():
                errors.append(f"broken local link: {source.relative_to(target)} -> {link}")

    referenced: set[str] = set()
    markdown_text = "\n".join(read_text(md) for md in target.rglob("*.md"))
    for file_path in target.rglob("*"):
        if file_path.is_file():
            rel = file_path.relative_to(target).as_posix()
            if rel in markdown_text:
                referenced.add(rel)

    for folder in ("references", "scripts"):
        dir_path = target / folder
        if not dir_path.exists():
            continue
        for file_path in dir_path.rglob("*"):
            if not file_path.is_file():
                continue
            rel = file_path.relative_to(target).as_posix()
            if rel not in referenced and file_path.name != "skill_spec.py":
                warnings.append(f"support file may be unreferenced: {rel}")

    return {
        "status": "pass" if not errors else "fail",
        "profile": profile,
        "errors": sorted(set(errors)),
        "warnings": sorted(set(warnings)),
        "inspected": sorted(set(inspected)),
        "portability": portability,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Run structural and portability gates for a skill package.")
    parser.add_argument("target", help="Path to a skill folder")
    parser.add_argument("--profile", choices=["portable", "openai"], default="portable")
    parser.add_argument("--json", dest="json_path", help="Optional JSON output path")
    args = parser.parse_args()

    report = run_gate(Path(args.target).resolve(), args.profile)
    if args.json_path:
        out = Path(args.json_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(report, indent=2, sort_keys=True))
    return 0 if report["status"] == "pass" else 1


if __name__ == "__main__":
    raise SystemExit(main())
