#!/usr/bin/env python3
"""Structural quality gate for skill packages created with skill-creator-juiced."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

try:
    import yaml
except Exception:  # pragma: no cover
    yaml = None

PLACEHOLDER_PATTERNS = [
    "TO" + "DO",
    "[" + "TO" + "DO",
    "replace" + " with actual",
    "placeholder" + " script",
    "example" + " asset",
    "api_" + "reference.md",
]

REQUIRED_BODY_TERMS = [
    "workflow",
    "output contract",
    "stop condition",
]

MARKDOWN_LINK_RE = re.compile(r"\[[^\]]+\]\(([^)]+)\)")


def read_frontmatter(text: str):
    if not text.startswith("---\n"):
        return None, "missing yaml frontmatter"
    match = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    if not match:
        return None, "invalid yaml frontmatter block"
    raw = match.group(1)
    if yaml is None:
        return None, "pyyaml is unavailable"
    try:
        data = yaml.safe_load(raw)
    except Exception as exc:
        return None, f"invalid yaml: {exc}"
    if not isinstance(data, dict):
        return None, "frontmatter is not a mapping"
    return data, None


def local_markdown_links(skill_root: Path, markdown_file: Path):
    text = markdown_file.read_text(encoding="utf-8")
    for target in MARKDOWN_LINK_RE.findall(text):
        if "://" in target or target.startswith("#") or target.startswith("mailto:"):
            continue
        path_part = target.split("#", 1)[0]
        if not path_part:
            continue
        yield markdown_file, path_part, (markdown_file.parent / path_part).resolve()


def run_gate(target: Path):
    errors = []
    warnings = []
    inspected = []

    if not target.exists() or not target.is_dir():
        return {"status": "fail", "errors": [f"target is not a directory: {target}"], "warnings": [], "inspected": []}

    skill_files = [p for p in target.rglob("SKILL.md") if ".git" not in p.parts]
    if len(skill_files) != 1:
        errors.append(f"expected exactly one SKILL.md, found {len(skill_files)}")
        return {"status": "fail", "errors": errors, "warnings": warnings, "inspected": [str(p) for p in skill_files]}

    skill_md = skill_files[0]
    inspected.append(str(skill_md))
    text = skill_md.read_text(encoding="utf-8")
    fm, fm_error = read_frontmatter(text)
    if fm_error:
        errors.append(fm_error)
    else:
        name = str(fm.get("name", "")).strip()
        description = str(fm.get("description", "")).strip()
        if not name:
            errors.append("frontmatter.name is required")
        elif not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", name):
            errors.append("frontmatter.name must be lowercase hyphen-case")
        if not description:
            errors.append("frontmatter.description is required")
        elif len(description) < 80:
            warnings.append("description may be too short to trigger accurately")
        if len(description) > 1024:
            errors.append("description exceeds 1024 characters")
        if set(fm.keys()) - {"name", "description"}:
            warnings.append("frontmatter has extra keys; chatgpt skills usually need only name and description")

    lower_text = text.lower()
    for term in REQUIRED_BODY_TERMS:
        if term not in lower_text:
            warnings.append(f"SKILL.md does not visibly include '{term}'")

    agents = target / "agents" / "openai.yaml"
    if agents.exists():
        inspected.append(str(agents))
    else:
        warnings.append("agents/openai.yaml is missing")

    for file_path in target.rglob("*"):
        if ".git" in file_path.parts:
            continue
        rel = file_path.relative_to(target)
        if "__pycache__" in file_path.parts or file_path.suffix in {".pyc", ".pyo"}:
            errors.append(f"cache/generated bytecode must not be packaged: {rel}")
            continue
        if not file_path.is_file():
            continue
        if rel.suffix.lower() in {".md", ".txt", ".py", ".yaml", ".yml", ".json"}:
            content = file_path.read_text(encoding="utf-8", errors="ignore")
            for pattern in PLACEHOLDER_PATTERNS:
                if pattern.lower() in content.lower() or pattern.lower() in str(rel).lower():
                    errors.append(f"placeholder/scaffold marker '{pattern}' found in {rel}")
                    break

    for md in target.rglob("*.md"):
        inspected.append(str(md))
        for source, link, resolved in local_markdown_links(target, md):
            if not str(resolved).startswith(str(target.resolve())):
                warnings.append(f"local link leaves package: {source.relative_to(target)} -> {link}")
            elif not resolved.exists():
                errors.append(f"broken local link: {source.relative_to(target)} -> {link}")

    referenced = set()
    for md in target.rglob("*.md"):
        content = md.read_text(encoding="utf-8", errors="ignore")
        for file_path in target.rglob("*"):
            if file_path.is_file() and file_path != md:
                rel = str(file_path.relative_to(target))
                if rel in content:
                    referenced.add(rel)

    for folder in ["references", "scripts", "examples", "evals"]:
        dir_path = target / folder
        if not dir_path.exists():
            continue
        for file_path in dir_path.rglob("*"):
            if file_path.is_file():
                rel = str(file_path.relative_to(target))
                if rel not in referenced and folder in {"references", "scripts"}:
                    warnings.append(f"support file may be unreferenced: {rel}")

    status = "pass" if not errors else "fail"
    return {
        "status": status,
        "errors": sorted(set(errors)),
        "warnings": sorted(set(warnings)),
        "inspected": sorted(set(inspected)),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Run structural quality gates for a skill package.")
    parser.add_argument("target", help="Path to a skill folder")
    parser.add_argument("--json", dest="json_path", help="Optional path to write JSON report")
    args = parser.parse_args()

    report = run_gate(Path(args.target).resolve())
    if args.json_path:
        Path(args.json_path).write_text(json.dumps(report, indent=2), encoding="utf-8")

    print(json.dumps(report, indent=2))
    return 0 if report["status"] == "pass" else 1


if __name__ == "__main__":
    sys.exit(main())
