#!/usr/bin/env python3
"""Write a canonical nomia ops.yaml scaffold with safe defaults."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from governance_contract import GOVERNANCE_STATES, LIFECYCLE_VALUES, PROFILE_VALUES
from nomia_utils import atomic_write_text


def render(
    spec_id: str | None,
    spec_id_provenance: str | None = None,
    profile: str | None = None,
    lifecycle: str | None = None,
    governance_status: str | None = None,
) -> str:
    spec_value = spec_id if spec_id else "null"
    provenance_value = f'"{spec_id_provenance}"' if spec_id_provenance else "null"
    profile_value = profile or ("standard" if spec_id else "unknown")
    lifecycle_value = lifecycle or ("intake" if spec_id else "unknown")
    governance_value = governance_status or ("intake" if spec_id else "unknown")
    return f"""## Generated by scripts/write_ops_scaffold.py.
## Fill only repository-truth values. Keep null, unknown, or empty lists when facts are missing.
## schema_version 2 is the canonical governed record. Legacy schema_version 1 is accepted only by governance-adapt as read-only input.

schema_version: 2
spec_id: {spec_value}
spec_id_provenance: {provenance_value}
privacy:
  classification: internal
  contains_personal_data: false
  contains_third_party_data: false
  contains_confidential_data: false
  contains_secrets: false
  redactions_applied: []
  redaction_method: none
  intended_audience:
    - governance-operator
  allowed_destinations:
    - local
  purpose: governance-record
  retention_days: 0
  external_share_allowed: false
  source_handoff_id: null
  source_reference: template://ops.yaml
  transformations:
    - synthetic-template
request:
  title: null
  requester: null
  requested_date: null
  source: unknown
  context: null
ownership:
  owner: null
  backup_owner: null
  stakeholders: []
  decision_maker: null
  watchers: []
planning:
  sprint: null
  bucket: unknown
  target_date: null
  commitment: unknown
  milestone: null
  rollout_target: null
business_priority:
  level: unknown
  urgency: unknown
  impact: unknown
  risk: unknown
  rationale: null
  cost_of_delay: null
status:
  state: {governance_value}
  summary: null
  updated_at: null
  confidence: unknown
  evidence_summary: null
  manual:
    summary: null
    updated_at: null
    source: null
  inferred:
    summary: null
    updated_at: null
    evidence: []
governance:
  profile: {profile_value}
  lifecycle: {lifecycle_value}
  status: {governance_value}
technical_state:
  planning:
    state: unknown
    source: null
    observed_at: null
  execution:
    state: unknown
    source: null
    observed_at: null
  validation:
    state: unknown
    source: null
    observed_at: null
release:
  state: unknown
  released_at: null
  evidence: []
dependencies: []
decision:
  state: unknown
  current: null
  evidence: []
handoffs:
  mago:
    state: unknown
    source: null
    observed_at: null
  magia:
    state: unknown
    source: null
    observed_at: null
provenance:
  updated_at: null
  facts: {{}}
  changes: []
timestamps:
  intake_at: null
  state_entered_at: null
  blocked_since: null
  decision_requested_at: null
  decision_at: null
  planning_started_at: null
  planning_ready_at: null
  execution_started_at: null
  execution_completed_at: null
  validation_observed_at: null
  released_at: null
  closed_at: null
  stakeholder_requested_at: null
  stakeholder_responded_at: null
blockers: []
risks: []
risk_history: []
replanning: []
tags: []
repos:
  candidate_impacted: []
links:
  mago: []
  magia: []
  external: []
"""


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Write a canonical nomia ops.yaml scaffold with safe defaults.")
    parser.add_argument("path", help="Destination path for ops.yaml.")
    parser.add_argument("--spec-id", help="Externally supplied spec id in spec-YYYY-MM-DD-feature-key format. Omit for off-repository drafts.")
    parser.add_argument("--spec-id-provenance", help="Evidence reference for the externally supplied spec id. Required with --spec-id.")
    parser.add_argument("--profile", choices=sorted(PROFILE_VALUES - {"unknown"}), help="Governance profile. Defaults to standard for repository records.")
    parser.add_argument("--lifecycle", choices=sorted(LIFECYCLE_VALUES - {"unknown"}), help="User-facing lifecycle stage. Defaults to intake for repository records.")
    parser.add_argument("--governance-status", choices=sorted(GOVERNANCE_STATES - {"unknown"}), help="Canonical governance status. Defaults to intake for repository records.")
    parser.add_argument("--list-data", help="YAML or JSON payload for scripts/update_template_lists.py.")
    parser.add_argument("--force", action="store_true", help="Overwrite the destination file if it already exists.")
    parser.add_argument("--dry-run", action="store_true", help="Print the canonical scaffold without writing a file.")
    args = parser.parse_args(argv)

    if args.spec_id and not args.spec_id_provenance:
        print("ERROR: --spec-id-provenance is required when --spec-id is provided")
        return 1
    if args.spec_id_provenance and not args.spec_id:
        print("ERROR: --spec-id-provenance requires --spec-id")
        return 1

    destination = Path(args.path).resolve()
    if destination.exists() and not args.force:
        print(f"ERROR: destination already exists: {destination}")
        print("Use --force to overwrite.")
        return 1

    rendered = render(args.spec_id, args.spec_id_provenance, args.profile, args.lifecycle, args.governance_status)
    if args.dry_run:
        print(rendered, end="")
        return 0
    atomic_write_text(destination, rendered)
    if args.list_data:
        from update_template_lists import main as update_lists_main

        result = update_lists_main([str(destination), "--data", args.list_data])
        if result != 0:
            return result

    print(f"OK: wrote {destination}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
