#!/usr/bin/env python3
"""Write a canonical nomia ops.yaml scaffold with safe defaults."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


def render(spec_id: str | None) -> str:
    spec_value = spec_id if spec_id else "null"
    return f"""## Generated by scripts/write_ops_scaffold.py.
## Fill only repository-truth values. Keep null, unknown, or empty lists when facts are missing.

schema_version: 1
spec_id: {spec_value}
request:
  title: null
  requester: null
  requested_date: null
  source: unknown
  context: null
ownership:
  owner: null
  backup_owner: null
  ## stakeholders/watchers entries must be non-empty strings.
  stakeholders: []
  decision_maker: null
  watchers: []
planning:
  sprint: null
  bucket: unknown
  target_date: null
  commitment: unknown
  milestone: null
  rollout_target: null
priority:
  level: unknown
  urgency: unknown
  impact: unknown
  risk: unknown
  rationale: null
  cost_of_delay: null
status:
  state: unknown
  summary: null
  updated_at: null
  confidence: unknown
  evidence_summary: null
  manual:
    summary: null
    updated_at: null
    source: null
  inferred:
    summary: null
    updated_at: null
    ## evidence entries must be non-empty strings describing supplied proof.
    evidence: []
## blocker item shape:
## - id: "blk-001"
##   summary: "Blocked by unresolved decision"
##   owner: "team-or-person-or-unknown"
##   needed_by: 2026-04-30
blockers: []
## risk item shape:
## - id: "risk-001"
##   summary: "Potential regression or delivery risk"
##   severity: medium
##   owner: "team-or-person-or-unknown"
risks: []
## replanning item shape:
## - date: 2026-04-30
##   changed_fields:
##     - target_date
##   from: 2026-04-30
##   to: 2026-05-07
##   reason: "Explain the material change"
##   impact: "Explain the delivery impact"
##   decision_maker: "team-or-person-or-unknown"
replanning: []
## tag entries must be non-empty strings. Prefer stable lowercase slugs.
tags: []
repos:
  ## candidate_impacted entries must be non-empty repository identifiers or repository-relative paths.
  candidate_impacted: []
links:
  ## links.mago and links.magia entries should be repository-relative paths when they point to local artifacts.
  ## links.external entries should be external URLs or stable external references.
  mago: []
  magia: []
  external: []
"""


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Write a canonical nomia ops.yaml scaffold with safe defaults.")
    parser.add_argument("path", help="Destination path for ops.yaml.")
    parser.add_argument("--spec-id", help="Concrete spec id in the form specNNN. Omit for off-repository drafts.")
    parser.add_argument("--list-data", help="YAML or JSON payload for scripts/update_template_lists.py.")
    parser.add_argument("--force", action="store_true", help="Overwrite the destination file if it already exists.")
    args = parser.parse_args(argv)

    destination = Path(args.path).resolve()
    if destination.exists() and not args.force:
        print(f"ERROR: destination already exists: {destination}")
        print("Use --force to overwrite.")
        return 1

    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(render(args.spec_id), encoding="utf-8")
    if args.list_data:
        from update_template_lists import main as update_lists_main

        result = update_lists_main([str(destination), "--data", args.list_data])
        if result != 0:
            return result

    print(f"OK: wrote {destination}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
